name: strava-flask
channels:
dependencies:
  - python>=3.5
  - requests
  - flask>=0.11.1
  - matplotlib
  - numpy
  - pip:
     - "--editable=git+https://github.com/jedman/stravalib.git#egg=stravalib"
